### ISSUE TITLE
sql schema of pyBiocFileCache and r-BiocFileCache are not compatible

### ISSUE THREAD

**Issue by khoroshevskyi** [epiviz/pyBiocFileCache#11]
Hi,
I found one anther issue. Unfortunately, schemas of Python and R packages are not compatible due to different schema.
**Python**:
![image](https://github.com/BiocPy/pyBiocFileCache/assets/41573628/67527e3f-b41a-4925-9ee8-ce15a901410a)
**R**:
![image](https://github.com/BiocPy/pyBiocFileCache/assets/41573628/e33d840e-ef90-4925-9476-d96b3507955d)

The differences are only VARCHAR/TEXT   
Could you please look into this issue?
Thanks!

**Comment by jkanche** [comment]
Thank you so much for the contribution. Its been a while since I looked at this particular package to check if the schema has been migrated on the R side. Additionally, I added you to the contributors list for the package.

This is merged and let me know if you run into any issues! Thanks again!

**Comment by jkanche** [comment]
v0.4.0 of the package contains these changes.
