### ISSUE TITLE
List all cached files

### ISSUE THREAD

**Issue by khoroshevskyi** [epiviz/pyBiocFileCache#18]
Currently, there is no function available to list all cached files.
Could you please add a method to the pybiocfilecache class to provide this functionality?
Thank you!

**Comment by jkanche** [comment]
`list_all` method should take care of it. Let me know if you run into issues. Thanks

**Comment by jkanche** [comment]
Had to rename this method in v0.5.0 release that I just published. Its now `list_resources` and many other bugs that were fixed with session management and cleanup of expired files. Its backwards compatible (🤞🏽), so i don't think it should cause any issues.
