### ISSUE TITLE
The "move" action deletes the original file even if it failed to be added to the cache

### ISSUE THREAD

**Issue by hargreaw** [epiviz/pyBiocFileCache#4]
When adding a file to the cache and using the "move" action the original file disappears if the file can't be added to the cache if the cache is busy.

Steps to reproduce:
1. Attempt to add many files to the cache using the "move" mode in parallel
2. Try to access files that failed to be added to the cache because it was busy

Workaround:
Use the "copy" action, delete original file if successfully added. Not ideal as when dealing with many large files in parallel this could lead to large amounts of temporary data duplication, it is also much slower than a "move" action.

**Comment by jkanche** [comment]
not sure if this is still relevant after many changes that happened to the repo. But feel free to provide an MRE of this issue if it still persists. Closing this for now.
