### ISSUE TITLE
Update sqlalchemy to >2.0

### ISSUE THREAD

**Issue by khoroshevskyi** [epiviz/pyBiocFileCache#6]
Hi, thank you for developing this package.

Currently, pyBiocFileCache requires `sqlalchemy.  < 2.0`. However, a new version of SQLAlchemy was released on January 26, 2023. Is it possible to update the requirements to support the latest version of SQLAlchemy?

**Comment by nsheff** [comment]
Hi @jkanche -- we're working to see if we can use pyBiocFileCache with bedbase, to see if we can have a single data source that can use a single cache that will work with both the R and python BiocFileCache.

we're using sqlalchemy 2+, which prevents us from using pyBiocFileCache

**Comment by jkanche** [comment]
Hi @khoroshevskyi and @nsheff, I'm gonna try to attempt it this weekend 🤞🏽 

> to see if we can have a single data source that can use a single cache that will work with both the R and python BiocFileCache.

I haven't kept up with Bioc's `BiocFileCache` lately and hopefully it's still the same.

**Comment by jkanche** [comment]
Please checkout v0.3.0 of the package and let me know if you run into any issues.

**Comment by khoroshevskyi** [comment]
Thank you, your changes solved this issue!
