### ISSUE TITLE
`asis` is not implemented to `BiocFileCache.add` `action` argument

### ISSUE THREAD

**Issue by khoroshevskyi** [epiviz/pyBiocFileCache#9]
Hello,

I'm currently working on integrating `pybiocfilecache` into our program, and I've encountered a new issue. It seems that the `action` argument in the `add` method of the `BiocFileCache` class is not implemented to accept `asis` as a value.
I would like to store my files as it is in the file system without moving or copping it to cache folder.

Could you please  take a look into this issue?

Thank you!

**Comment by jkanche** [comment]
Hi, Let me take a look at this later this week. I am trying to finish a couple of other things this week so may not be able to get to this right away.

**Comment by jkanche** [comment]
hello there, @khoroshevskyi can you give 0.3.1 a try and let me know if you run into any issues? Thanks!

**Comment by khoroshevskyi** [comment]
Thanks, I tried to use it today, and every think working so far.
Thank you!
